# Generated by Django 5.1.7 on 2025-03-27 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0004_customersupportrepresentative_assigned_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportrepresentative',
            name='role',
            field=models.CharField(default='Support Agent', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'jpeg', 'docx'])]),
        ),
    ]
