# Generated by Django 5.1.7 on 2025-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0005_customersupportrepresentative_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('leak', 'Gas Leak'), ('billing', 'Billing Inquiry'), ('new', 'New Connection'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
